name: Keep Render Instance Alive

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Keep Alive Request
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://artistismit.onrender.com
